cypher = """
MATCH p = (a:A)-[:REL]->(b:B)
RETURN length(p) AS l
"""

[[graphs]]
triples = [
  ["ex:a1", "rdf:type", "ex:A"],
  ["ex:b1", "rdf:type", "ex:B"],
  ["ex:a1", "ex:REL", "ex:b1"],
]
expected = [[{ l = "1" }]]
