impl TranslationState {
    // ── MATCH clause ─────────────────────────────────────────────────────────

    /// Translate a `MATCH` or `OPTIONAL MATCH` clause into a graph pattern plus
    /// an optional filter expression (from the inline `WHERE`).
    fn translate_match_clause(
        &mut self,
        m: &MatchClause,
        _extra: &mut Vec<TriplePattern>,
    ) -> Result<(GraphPattern, Option<SparExpr>, Vec<TriplePattern>), PolygraphError> {
        let mut triples: Vec<TriplePattern> = Vec::new();
        let mut path_patterns: Vec<GraphPattern> = Vec::new();

        // Clear the per-MATCH relationship isomorphism tracker.
        self.iso_hops.clear();

        self.translate_pattern_list(&m.pattern, &mut triples, &mut path_patterns)?;

        // Combine BGP triples + path patterns into a single graph pattern.
        let bgp = GraphPattern::Bgp { patterns: triples };
        let mut combined = path_patterns.into_iter().fold(bgp, join_patterns);

        // Apply pairwise relationship-isomorphism FILTERs.
        let iso_filters = self.generate_iso_filters();
        combined = apply_filters(combined, iso_filters.into_iter());

        // Apply any pending property-equality FILTERs generated by
        // translate_node_pattern_with_term for complex inline property expressions.
        let prop_filters: Vec<SparExpr> = std::mem::take(&mut self.pending_prop_filters);
        combined = apply_filters(combined, prop_filters.into_iter());

        // Note: pending_match_filters (for re-used edge sameTerm constraints) are
        // NOT applied here — they are applied by the Clause::Match handler in
        // translate_query AFTER joining with the preceding match patterns, so that
        // outer variables (from previous MATCH clauses) are in scope for the FILTER.

        // Use a local buffer for WHERE-clause property-access triples so they can
        // be applied as OPTIONAL LeftJoins by the caller (Cypher null semantics:
        // a missing property evaluates to null rather than filtering the row out).
        let mut where_extra: Vec<TriplePattern> = Vec::new();
        let filter = if let Some(wc) = &m.where_ {
            Some(self.translate_expr(&wc.expression, &mut where_extra)?)
        } else {
            None
        };

        Ok((combined, filter, where_extra))
    }

    // ── Pattern translation ───────────────────────────────────────────────────

    fn translate_pattern_list(
        &mut self,
        list: &PatternList,
        triples: &mut Vec<TriplePattern>,
        path_patterns: &mut Vec<GraphPattern>,
    ) -> Result<(), PolygraphError> {
        for pattern in &list.0 {
            self.translate_pattern(pattern, triples, path_patterns)?;
        }
        Ok(())
    }

    fn translate_pattern(
        &mut self,
        pattern: &Pattern,
        triples: &mut Vec<TriplePattern>,
        path_patterns: &mut Vec<GraphPattern>,
    ) -> Result<(), PolygraphError> {
        // Walk the element list: [Node, Rel, Node, Rel, Node, …]
        // We need to pair each Relationship with its surrounding nodes.
        let elements = &pattern.elements;

        // Track named path hop counts and node vars for length(p) / nodes(p) resolution.
        if let Some(ref path_var) = pattern.variable {
            let hops = elements
                .iter()
                .filter(|e| matches!(e, PatternElement::Relationship(_)))
                .count() as u64;
            self.path_hops.insert(path_var.clone(), hops);
        }

        // Pre-compute a stable TermPattern for every node element.  Anonymous nodes
        // (no variable) get a fresh SPARQL variable so the same term is reused for
        // both the relationship triple and the sentinel / label triples.
        let node_terms: Vec<TermPattern> = elements
            .iter()
            .map(|e| match e {
                PatternElement::Node(n) => match &n.variable {
                    Some(v) => Variable::new_unchecked(v.clone()).into(),
                    None => {
                        let fresh = self.fresh_var("anon");
                        fresh.into()
                    }
                },
                _ => Variable::new_unchecked("__unused_rel_slot").into(),
            })
            .collect();

        // Store node variables for path if named.
        if let Some(ref path_var) = pattern.variable {
            let nvars: Vec<Variable> = elements
                .iter()
                .enumerate()
                .filter_map(|(idx, e)| {
                    if matches!(e, PatternElement::Node(_)) {
                        if let TermPattern::Variable(v) = &node_terms[idx] {
                            return Some(v.clone());
                        }
                    }
                    None
                })
                .collect();
            self.path_node_vars.insert(path_var.clone(), nvars);
        }

        let mut i = 0;
        while i < elements.len() {
            match &elements[i] {
                PatternElement::Node(n) => {
                    let term = node_terms[i].clone();
                    self.translate_node_pattern_with_term(n, &term, triples)?;
                    i += 1;
                }
                PatternElement::Relationship(r) => {
                    let src = if i > 0 {
                        node_terms[i - 1].clone()
                    } else {
                        Variable::new_unchecked("__anon").into()
                    };
                    let dst = node_terms
                        .get(i + 1)
                        .cloned()
                        .unwrap_or_else(|| Variable::new_unchecked("__anon").into());
                    // Save pending filter count to detect re-use after the call.
                    let filters_before = self.pending_match_filters.len();
                    self.translate_relationship_pattern(r, &src, &dst, triples, path_patterns)?;
                    // If a reuse filter was pushed, also add endpoint-exclusion
                    // filters for adjacent variable-length paths so that the varlen
                    // traversals do not re-use the specific bound edge r.
                    if self.pending_match_filters.len() > filters_before {
                        if let Some(ref var_name) = r.variable {
                            if let Some(prior) = self.edge_map.get(var_name).cloned() {
                                let ps = term_to_sparexpr(&prior.src);
                                let pd = term_to_sparexpr(&prior.dst);
                                // Left adjacent varlen: elements[i-2] with range Some
                                let left_outer: Option<TermPattern> = if i >= 2 {
                                    if let Some(PatternElement::Relationship(lr)) =
                                        elements.get(i.wrapping_sub(2))
                                    {
                                        if lr.range.is_some() {
                                            node_terms.get(i.wrapping_sub(3)).cloned()
                                        } else {
                                            None
                                        }
                                    } else {
                                        None
                                    }
                                } else {
                                    None
                                };
                                // Right adjacent varlen: elements[i+2] with range Some
                                let right_outer: Option<TermPattern> = {
                                    if let Some(PatternElement::Relationship(rr)) =
                                        elements.get(i + 2)
                                    {
                                        if rr.range.is_some() {
                                            node_terms.get(i + 3).cloned()
                                        } else {
                                            None
                                        }
                                    } else {
                                        None
                                    }
                                };
                                // Emit filters: exclude paths where adjacent varlen endpoint
                                // pair matches r's src/dst (which would mean the varlen
                                // traversed the specific bound edge r, violating rel uniqueness).
                                let mk_exclusion_filter = |a: SparExpr, b: SparExpr| {
                                    SparExpr::And(
                                        Box::new(SparExpr::Not(Box::new(SparExpr::And(
                                            Box::new(SparExpr::SameTerm(
                                                Box::new(a.clone()),
                                                Box::new(ps.clone()),
                                            )),
                                            Box::new(SparExpr::SameTerm(
                                                Box::new(b.clone()),
                                                Box::new(pd.clone()),
                                            )),
                                        )))),
                                        Box::new(SparExpr::Not(Box::new(SparExpr::And(
                                            Box::new(SparExpr::SameTerm(
                                                Box::new(a),
                                                Box::new(pd.clone()),
                                            )),
                                            Box::new(SparExpr::SameTerm(
                                                Box::new(b),
                                                Box::new(ps.clone()),
                                            )),
                                        )))),
                                    )
                                };
                                if let Some(n_term) = left_outer {
                                    let n_e = term_to_sparexpr(&n_term);
                                    let a3_e = term_to_sparexpr(&src);
                                    self.pending_match_filters
                                        .push(mk_exclusion_filter(n_e, a3_e));
                                }
                                if let Some(m_term) = right_outer {
                                    let a4_e = term_to_sparexpr(&dst);
                                    let m_e = term_to_sparexpr(&m_term);
                                    self.pending_match_filters
                                        .push(mk_exclusion_filter(a4_e, m_e));
                                }
                            }
                        }
                    }
                    i += 1;
                }
            }
        }
        Ok(())
    }

    fn translate_node_pattern_with_term(
        &mut self,
        node: &NodePattern,
        node_var: &TermPattern,
        triples: &mut Vec<TriplePattern>,
    ) -> Result<(), PolygraphError> {
        // Register named node variables for schema classification.
        if let Some(ref name) = node.variable {
            self.node_vars.insert(name.clone());
        }

        // One triple per label: `?n rdf:type <base:Label>`
        // In skip_writes mode, skip labels that are being REMOVED (they won't
        // be present in the graph after the REMOVE UPDATE has run).
        let skip_labels: std::collections::HashSet<String> = if self.skip_write_clauses {
            if let Some(ref vname) = node.variable {
                if let Some(removed) = self.remove_tracked_labels.get(vname.as_str()) {
                    removed.iter().cloned().collect()
                } else {
                    Default::default()
                }
            } else {
                Default::default()
            }
        } else {
            Default::default()
        };

        for label in &node.labels {
            if skip_labels.contains(label.as_str()) {
                continue; // label is being removed; don't filter by it
            }
            triples.push(TriplePattern {
                subject: node_var.clone(),
                predicate: self.rdf_type().into(),
                object: self.iri(label).into(),
            });
        }

        // Inline properties: `?n <base:prop> <literal>`
        let has_props = node
            .properties
            .as_ref()
            .map(|p| !p.is_empty())
            .unwrap_or(false);
        if let Some(props) = &node.properties {
            for (key, val_expr) in props {
                match self.expr_to_ground_term(val_expr) {
                    Ok(obj) => {
                        triples.push(TriplePattern {
                            subject: node_var.clone(),
                            predicate: self.iri(key).into(),
                            object: obj,
                        });
                    }
                    Err(_) => {
                        // Complex expression (e.g., variable + literal, bound variable).
                        // Add a fresh variable as the property value object, then store an
                        // equality FILTER so the caller can apply it as a WHERE condition.
                        let fresh = self.fresh_var(&format!("__prop_{key}"));
                        triples.push(TriplePattern {
                            subject: node_var.clone(),
                            predicate: self.iri(key).into(),
                            object: TermPattern::Variable(fresh.clone()),
                        });
                        let mut filter_extra: Vec<TriplePattern> = Vec::new();
                        if let Ok(val_sparql) = self.translate_expr(val_expr, &mut filter_extra) {
                            if !filter_extra.is_empty() {
                                // Property access triples from the value expression — add to BGP
                                triples.extend(filter_extra);
                            }
                            self.pending_prop_filters.push(SparExpr::Equal(
                                Box::new(SparExpr::Variable(fresh)),
                                Box::new(val_sparql),
                            ));
                        } else {
                            return Err(PolygraphError::UnsupportedFeature {
                                feature: "complex expression in inline property map (Phase 4)"
                                    .to_string(),
                            });
                        }
                    }
                }
            }
        }

        // Unconstrained node (no labels, no properties): emit a node-existence
        // sentinel so the variable is bound to real graph nodes rather than
        // returning 1 empty row from an empty BGP.
        // Convention: every graph node has exactly one `<base:__node> <base:__node>` triple.
        // Also add sentinel when ALL labels have been skipped due to REMOVE tracking.
        let effective_label_count = node
            .labels
            .iter()
            .filter(|l| !skip_labels.contains(l.as_str()))
            .count();
        if effective_label_count == 0 && !has_props {
            triples.push(TriplePattern {
                subject: node_var.clone(),
                predicate: self.iri("__node").into(),
                object: self.iri("__node").into(),
            });
        }

        Ok(())
    }

    fn translate_relationship_pattern(
        &mut self,
        rel: &RelationshipPattern,
        src: &TermPattern,
        dst: &TermPattern,
        triples: &mut Vec<TriplePattern>,
        path_patterns: &mut Vec<GraphPattern>,
    ) -> Result<(), PolygraphError> {
        use crate::ast::cypher::Direction;
        use spargebra::algebra::PropertyPathExpression as PPE;

        // Build predicate: NamedNode or PropertyPath with |/*/+/?
        let has_range = rel.range.is_some();
        let multi_type = rel.rel_types.len() > 1;

        if rel.rel_types.is_empty() && !has_range {
            // No type constraint, no range: emit an anonymous predicate variable (no path).
            let pred_var = match &rel.variable {
                Some(v) => Variable::new_unchecked(format!("{}_pred", v)),
                None => self.fresh_var("rel"),
            };
            let pred_term: spargebra::term::NamedNodePattern = pred_var.clone().into();

            // Build RDF 1.2 reification-based patterns for inline relationship properties
            // (e.g. [r {name: 'r1'}]).  For untyped relationships the predicate is
            // a variable so the triple term is <<( ?s ?pred ?o )>>.
            let prop_anno = if self.rdf_star {
                if let Some(ref props) = rel.properties {
                    let mut pairs = Vec::new();
                    for (key, val_expr) in props {
                        let obj = self.expr_to_ground_term(val_expr)?;
                        pairs.push((self.iri(key), obj));
                    }
                    pairs
                } else {
                    Vec::new()
                }
            } else {
                Vec::new()
            };

            // Generate a fresh reifier variable once; reused across both UNION branches.
            // The fresh var is None when there are no properties (skipped).
            let anno_reif_var = if prop_anno.is_empty() {
                None
            } else {
                Some(self.fresh_var("__rdf12_reif"))
            };

            // Helper: build RDF 1.2 reification patterns for inline properties.
            // ?reif rdf:reifies <<( s pred o )>> . ?reif <prop> val . ...
            let anno_triples = |s: &TermPattern, o: &TermPattern| -> Vec<TriplePattern> {
                let Some(ref reif_var) = anno_reif_var else {
                    return Vec::new();
                };
                rdf_mapping::rdf_star::all_property_triples(
                    s.clone(),
                    pred_term.clone(),
                    o.clone(),
                    &prop_anno,
                    reif_var.clone(),
                )
            };

            // Check if this relationship variable was already bound in the current
            // generation (no WITH since first binding).
            // If so, we use sameTerm endpoint filters to constrain re-use.
            let reuse_prior: Option<EdgeInfo> = rel.variable.as_ref().and_then(|rv| {
                self.edge_map.get(rv.as_str()).cloned().and_then(|e| {
                    if e.binding_generation == self.with_generation {
                        Some(e)
                    } else {
                        None
                    }
                })
            });
            // Also compute convenience alias for Direction::Both eid detection.
            let reuse_eid: Option<Variable> = reuse_prior.as_ref().and_then(|e| e.eid_var.clone());

            match rel.direction {
                Direction::Left => {
                    if reuse_eid.is_none() {
                        if let Some(ref var_name) = rel.variable {
                            // Named untyped LEFT relationship: put the triple and the BIND
                            // in the SAME group graph pattern so BIND can see ?pred and endpoints.
                            let eid = Variable::new_unchecked(format!("__eid_{}", var_name));
                            let pred_expr = SparExpr::Variable(pred_var.clone());
                            // Canonical stored-triple order: subject=dst, predicate=?pred, object=src.
                            let eid_expr = build_edge_id_expr(dst, pred_expr, src);
                            let rel_bgp = GraphPattern::Bgp {
                                patterns: vec![TriplePattern {
                                    subject: dst.clone(),
                                    predicate: pred_term.clone(),
                                    object: src.clone(),
                                }],
                            };
                            path_patterns.push(GraphPattern::Extend {
                                inner: Box::new(rel_bgp),
                                variable: eid,
                                expression: eid_expr,
                            });
                            triples.extend(anno_triples(dst, src));
                        } else {
                            triples.push(TriplePattern {
                                subject: dst.clone(),
                                predicate: pred_term.clone(),
                                object: src.clone(),
                            });
                            triples.extend(anno_triples(dst, src));
                        }
                    } else {
                        triples.push(TriplePattern {
                            subject: dst.clone(),
                            predicate: pred_term.clone(),
                            object: src.clone(),
                        });
                        triples.extend(anno_triples(dst, src));
                    }
                }
                Direction::Right => {
                    if reuse_eid.is_none() {
                        if let Some(ref var_name) = rel.variable {
                            // Named untyped RIGHT relationship: put the triple and the BIND
                            // in the SAME group graph pattern so BIND can see ?pred and endpoints.
                            let eid = Variable::new_unchecked(format!("__eid_{}", var_name));
                            let pred_expr = SparExpr::Variable(pred_var.clone());
                            let eid_expr = build_edge_id_expr(src, pred_expr, dst);
                            let rel_bgp = GraphPattern::Bgp {
                                patterns: vec![TriplePattern {
                                    subject: src.clone(),
                                    predicate: pred_term.clone(),
                                    object: dst.clone(),
                                }],
                            };
                            path_patterns.push(GraphPattern::Extend {
                                inner: Box::new(rel_bgp),
                                variable: eid,
                                expression: eid_expr,
                            });
                            triples.extend(anno_triples(src, dst));
                        } else {
                            triples.push(TriplePattern {
                                subject: src.clone(),
                                predicate: pred_term.clone(),
                                object: dst.clone(),
                            });
                            triples.extend(anno_triples(src, dst));
                        }
                    } else {
                        triples.push(TriplePattern {
                            subject: src.clone(),
                            predicate: pred_term.clone(),
                            object: dst.clone(),
                        });
                        triples.extend(anno_triples(src, dst));
                    }
                }
                Direction::Both => {
                    // For re-used edges (same generation, no intervening WITH), emit a
                    // simple UNION of the two directed triples, and push the endpoint
                    // sameTerm constraint to pending_match_filters.  The pending filter
                    // is applied AFTER all path_patterns are joined into the MATCH
                    // combined pattern, so it is in the OUTER scope where variables from
                    // preceding MATCH clauses (e.g. ?__anon_0, ?__anon_1) are visible.
                    // NB: putting the sameTerm FILTER inside the UNION branches does NOT
                    // work because SPARQL nested-group FILTERs do not see outer variables.
                    if let Some(ref prior) = reuse_prior {
                        let constrained_pred: spargebra::term::NamedNodePattern =
                            if prior.pred_var.is_none() {
                                // Typed prior: pin the predicate to the known named node.
                                spargebra::term::NamedNodePattern::NamedNode(prior.pred.clone())
                            } else {
                                // Untyped prior: shared r_pred variable name provides constraint.
                                pred_term.clone()
                            };
                        // UNION of forward and backward triples (no inner sameTerm FILTER).
                        let fwd_bgp = GraphPattern::Bgp {
                            patterns: vec![TriplePattern {
                                subject: src.clone(),
                                predicate: constrained_pred.clone(),
                                object: dst.clone(),
                            }],
                        };
                        // Backward branch: self-loop guard only.
                        let bwd_bgp_inner = GraphPattern::Bgp {
                            patterns: vec![TriplePattern {
                                subject: dst.clone(),
                                predicate: constrained_pred,
                                object: src.clone(),
                            }],
                        };
                        let sl_filter = if let (
                            TermPattern::Variable(s),
                            TermPattern::Variable(d),
                        ) = (src, dst)
                        {
                            Some(SparExpr::Not(Box::new(SparExpr::Equal(
                                Box::new(SparExpr::Variable(s.clone())),
                                Box::new(SparExpr::Variable(d.clone())),
                            ))))
                        } else {
                            None
                        };
                        let bwd_bgp = if let Some(f) = sl_filter {
                            GraphPattern::Filter {
                                expr: f,
                                inner: Box::new(bwd_bgp_inner),
                            }
                        } else {
                            bwd_bgp_inner
                        };
                        path_patterns.push(GraphPattern::Union {
                            left: Box::new(fwd_bgp),
                            right: Box::new(bwd_bgp),
                        });
                        // Push the sameTerm constraint as a deferred outer FILTER.
                        // (sameTerm works for blank nodes; = works for IRIs too.)
                        let prior_src_e = term_to_sparexpr(&prior.src);
                        let prior_dst_e = term_to_sparexpr(&prior.dst);
                        let cur_src_e = term_to_sparexpr(src);
                        let cur_dst_e = term_to_sparexpr(dst);
                        // fwd match: anon3 = prior_src AND anon4 = prior_dst
                        let fwd_f = SparExpr::And(
                            Box::new(SparExpr::SameTerm(
                                Box::new(cur_src_e.clone()),
                                Box::new(prior_src_e.clone()),
                            )),
                            Box::new(SparExpr::SameTerm(
                                Box::new(cur_dst_e.clone()),
                                Box::new(prior_dst_e.clone()),
                            )),
                        );
                        // bwd match: anon3 = prior_dst AND anon4 = prior_src (AND != for self-loop)
                        let bwd_f = SparExpr::And(
                            Box::new(SparExpr::SameTerm(
                                Box::new(cur_src_e.clone()),
                                Box::new(prior_dst_e.clone()),
                            )),
                            Box::new(SparExpr::And(
                                Box::new(SparExpr::SameTerm(
                                    Box::new(cur_dst_e.clone()),
                                    Box::new(prior_src_e.clone()),
                                )),
                                Box::new(SparExpr::Not(Box::new(SparExpr::SameTerm(
                                    Box::new(cur_src_e),
                                    Box::new(cur_dst_e),
                                )))),
                            )),
                        );
                        self.pending_match_filters
                            .push(SparExpr::Or(Box::new(fwd_f), Box::new(bwd_f)));
                        // Do not re-register in edge_map or track iso_hop for re-use.
                        return Ok(());
                    }

                    // First binding (normal path): UNION of both directions + eid BIND.
                    let mut fwd_patterns = vec![TriplePattern {
                        subject: src.clone(),
                        predicate: pred_term.clone(),
                        object: dst.clone(),
                    }];
                    fwd_patterns.extend(anno_triples(src, dst));
                    let fwd = GraphPattern::Bgp {
                        patterns: fwd_patterns,
                    };
                    let mut bwd_patterns = vec![TriplePattern {
                        subject: dst.clone(),
                        predicate: pred_term.clone(),
                        object: src.clone(),
                    }];
                    bwd_patterns.extend(anno_triples(dst, src));
                    let bwd_triple = GraphPattern::Bgp {
                        patterns: bwd_patterns,
                    };
                    // Prevent duplicate for self-loops.
                    let filter_expr =
                        if let (TermPattern::Variable(s), TermPattern::Variable(d)) = (src, dst) {
                            Some(SparExpr::Not(Box::new(SparExpr::Equal(
                                Box::new(SparExpr::Variable(s.clone())),
                                Box::new(SparExpr::Variable(d.clone())),
                            ))))
                        } else {
                            None
                        };
                    let bwd = if let Some(f) = filter_expr {
                        GraphPattern::Filter {
                            expr: f,
                            inner: Box::new(bwd_triple),
                        }
                    } else {
                        bwd_triple
                    };
                    // If the relationship has a name, BIND a synthetic edge-identity
                    // variable in each UNION branch.  The canonical form uses the actual
                    // stored-triple component order (subject, predicate, object) so that
                    // forward and reverse matches of the same triple yield the same ID.
                    let (fwd, bwd) = if let Some(rel_var_name) = &rel.variable {
                        let eid = Variable::new_unchecked(format!("__eid_{}", rel_var_name));
                        let pred_expr = SparExpr::Variable(pred_var.clone());
                        let fwd_eid = build_edge_id_expr(src, pred_expr.clone(), dst);
                        let bwd_eid = build_edge_id_expr(dst, pred_expr, src);
                        let fwd = GraphPattern::Extend {
                            inner: Box::new(fwd),
                            variable: eid.clone(),
                            expression: fwd_eid,
                        };
                        let bwd = GraphPattern::Extend {
                            inner: Box::new(bwd),
                            variable: eid,
                            expression: bwd_eid,
                        };
                        (fwd, bwd)
                    } else {
                        (fwd, bwd)
                    };
                    path_patterns.push(GraphPattern::Union {
                        left: Box::new(fwd),
                        right: Box::new(bwd),
                    });
                }
            }
            // Register in edge_map so type(r) and r.prop can resolve.
            // For re-used edges (reuse_eid is Some), keep the original edge_map entry.
            if reuse_eid.is_none() {
                if let Some(ref var_name) = rel.variable {
                    let eid = Variable::new_unchecked(format!("__eid_{}", var_name));
                    // Store the actual RDF subject/object order based on direction.
                    // For Left, the relationship triple is (dst -> src), so swap.
                    let (map_src, map_dst) = match rel.direction {
                        Direction::Left => (dst.clone(), src.clone()),
                        _ => (src.clone(), dst.clone()),
                    };
                    self.edge_map.insert(
                        var_name.clone(),
                        EdgeInfo {
                            src: map_src,
                            pred: NamedNode::new_unchecked("urn:polygraph:untyped"),
                            pred_var: Some(pred_var.clone()),
                            dst: map_dst,
                            reif_var: None,
                            null_check_var: None,
                            eid_var: Some(eid),
                            binding_generation: self.with_generation,
                        },
                    );
                }
            }
            // Track for pairwise isomorphism filter generation (skip for re-used edges).
            if reuse_eid.is_none() {
                use spargebra::term::NamedNodePattern;
                let pv = NamedNodePattern::Variable(pred_var);
                let instances: Vec<EdgeIsoSlot> = match rel.direction {
                    Direction::Right => vec![(src.clone(), pv, dst.clone())],
                    Direction::Left => vec![(dst.clone(), pv, src.clone())],
                    Direction::Both => vec![
                        (src.clone(), pv.clone(), dst.clone()),
                        (dst.clone(), pv, src.clone()),
                    ],
                };
                self.track_iso_hop(instances);
            }
            return Ok(());
        }

        // Build base path expression (single type, multi-type alt, or NegatedPropertySet for untyped).
        let base_ppe: PPE = if rel.rel_types.is_empty() {
            // Untyped variable-length: match any predicate except internal markers.
            // Exclude rdf:type and __node to avoid traversing property/label triples.
            PPE::NegatedPropertySet(vec![NamedNode::new_unchecked(RDF_TYPE), self.iri("__node")])
        } else if multi_type {
            let types: Vec<PPE> = rel
                .rel_types
                .iter()
                .map(|t| PPE::from(self.iri(t)))
                .collect();
            types
                .into_iter()
                .reduce(|a, b| PPE::Alternative(Box::new(a), Box::new(b)))
                .expect("at least 2 types")
        } else {
            PPE::from(self.iri(&rel.rel_types[0]))
        };

        // Apply range quantifier if present.
        let ppe: Option<PPE> = if has_range {
            let range = rel.range.as_ref().unwrap();

            // Special case: varlen with property constraints → bounded unrolling with
            // RDF-star per-hop annotation filters.
            if rel.properties.is_some() && self.rdf_star && !rel.rel_types.is_empty() {
                let lower = range.lower.unwrap_or(1).max(1);
                let upper = range.upper.unwrap_or(lower + 10);
                self.emit_bounded_path_union_with_props(
                    rel,
                    src,
                    dst,
                    lower,
                    upper,
                    path_patterns,
                )?;
                return Ok(());
            }

            let q = match (range.lower, range.upper) {
                // * (bare star) = 1 or more hops in openCypher
                (None, None) => PPE::OneOrMore(Box::new(base_ppe)),
                // *0.. = zero or more hops
                (Some(0), None) => PPE::ZeroOrMore(Box::new(base_ppe)),
                // *1..
                (Some(1), None) => PPE::OneOrMore(Box::new(base_ppe)),
                // *0..1 = zero or one hop — ZeroOrOne SPARQL path.
                (Some(0), Some(1)) => PPE::ZeroOrOne(Box::new(base_ppe)),
                // *1..1 = exact 1 hop, treat as simple triple
                (Some(1), Some(1)) => {
                    if rel.rel_types.is_empty() {
                        // Untyped *1..1: use NPS as a 1-hop path
                        base_ppe
                    } else {
                        // Typed *1..1: emit as regular triple (no range modifier).
                        let pred = self.iri(&rel.rel_types[0]);
                        self.emit_edge_triple(rel, src, dst, pred, triples, path_patterns)?;
                        return Ok(());
                    }
                }
                // Bounded ranges like *M..N — unroll as UNION of fixed-length chains.
                // Note: unspecified lower bound defaults to 1 in openCypher (not 0),
                // so *..0 = empty, *..1 = exactly-1-hop, *..2 = 1-or-2 hops, etc.
                (lo, hi) => {
                    let lower = lo.unwrap_or(1);
                    let upper = match hi {
                        Some(u) => u,
                        None => {
                            // *N.. (lower only): compose path for minimum bound.
                            if lower <= 1 {
                                let q = if lower == 0 {
                                    PPE::ZeroOrMore(Box::new(base_ppe))
                                } else {
                                    PPE::OneOrMore(Box::new(base_ppe))
                                };
                                let (subj, obj) = match rel.direction {
                                    Direction::Left => (dst.clone(), src.clone()),
                                    _ => (src.clone(), dst.clone()),
                                };
                                // For Left: subj=dst, obj=src (already swapped); use forward
                                // path — no PPE::Reverse needed since the swap is sufficient.
                                path_patterns.push(GraphPattern::Path {
                                    subject: subj,
                                    path: q,
                                    object: obj,
                                });
                                return Ok(());
                            }
                            // *N.. with N>1: bounded unrolling from N to N+5
                            // SPARQL property paths can't enforce min-hop constraints.
                            let cap = lower + 5;
                            self.emit_bounded_path_union(
                                rel,
                                src,
                                dst,
                                &base_ppe,
                                lower,
                                cap,
                                triples,
                                path_patterns,
                            )?;
                            return Ok(());
                        }
                    };
                    // Build UNION of hop counts from lower..=upper.
                    self.emit_bounded_path_union(
                        rel,
                        src,
                        dst,
                        &base_ppe,
                        lower,
                        upper,
                        triples,
                        path_patterns,
                    )?;
                    return Ok(());
                }
            };
            Some(q)
        } else {
            None
        };

        if let Some(path) = ppe {
            // Emit a GraphPattern::Path
            let (subj, obj) = match rel.direction {
                Direction::Left => (dst.clone(), src.clone()),
                _ => (src.clone(), dst.clone()),
            };
            // For Left: subj=dst, obj=src (already swapped above) — use forward path.
            // Adding PPE::Reverse on top of the swap causes double-inversion (wrong direction).
            // For Both: effective_base was already built as Alternative(base, ^base) in the
            // quantifier dispatch above; no further Alternative wrapping is needed here.
            let path = if rel.direction == Direction::Both {
                PPE::Alternative(
                    Box::new(path.clone()),
                    Box::new(PPE::Reverse(Box::new(path))),
                )
            } else {
                path
            };
            let mut path_gp = GraphPattern::Path {
                subject: subj,
                path,
                object: obj,
            };
            // For untyped paths (NegatedPropertySet), filter out literal endpoints
            // since NPS also matches property predicates leading to literals.
            if rel.rel_types.is_empty() {
                let endpoint = match rel.direction {
                    Direction::Left => src,
                    _ => dst,
                };
                if let TermPattern::Variable(v) = endpoint {
                    path_gp = GraphPattern::Filter {
                        expr: SparExpr::Not(Box::new(SparExpr::FunctionCall(
                            spargebra::algebra::Function::IsLiteral,
                            vec![SparExpr::Variable(v.clone())],
                        ))),
                        inner: Box::new(path_gp),
                    };
                }
            }
            // Register edge variable in edge_map (no inline properties on path patterns).
            // For varlen paths, bind a marker variable so count(r) works.
            if let Some(ref var_name) = rel.variable {
                let pred = if rel.rel_types.is_empty() {
                    NamedNode::new_unchecked("urn:polygraph:untyped")
                } else {
                    self.iri(&rel.rel_types[0])
                };
                let marker = self.fresh_var(&format!("{}_bound", var_name));
                path_gp = GraphPattern::Extend {
                    inner: Box::new(path_gp),
                    variable: marker.clone(),
                    expression: SparExpr::Literal(SparLit::new_typed_literal(
                        "true",
                        NamedNode::new_unchecked(XSD_BOOLEAN),
                    )),
                };
                self.edge_map.insert(
                    var_name.clone(),
                    EdgeInfo {
                        src: src.clone(),
                        pred,
                        pred_var: None,
                        dst: dst.clone(),
                        reif_var: None,
                        null_check_var: Some(marker),
                        eid_var: None,
                        binding_generation: self.with_generation,
                    },
                );
                // Track varlen bounds for last(r) / head(r) resolution.
                if let Some(range) = &rel.range {
                    let lower = range.lower.unwrap_or(0);
                    let upper = range.upper.unwrap_or(u64::MAX);
                    self.varlen_rel_scope
                        .insert(var_name.clone(), (lower, upper));
                }
            }
            // For unbounded variable-length paths (no upper bound), add extra
            // rows for self-loop nodes, since Cypher semantics count distinct
            // PATHS (not just endpoint pairs) and a self-loop on the endpoint
            // creates a second path.  SPARQL property paths only return distinct
            // endpoint pairs, so the extra row is emitted via a UNION that requires
            // a self-loop triple at the far endpoint.
            let is_unbounded = rel.range.as_ref().map_or(false, |r| r.upper.is_none());
            let far_end: &TermPattern = match rel.direction {
                Direction::Left => src,
                _ => dst,
            };
            if is_unbounded {
                if let TermPattern::Variable(far_var) = far_end {
                    let sl_pred_var = self.fresh_var("sl_pred");
                    let sl_gp = GraphPattern::Bgp {
                        patterns: vec![TriplePattern {
                            subject: far_var.clone().into(),
                            predicate: sl_pred_var.into(),
                            object: far_var.clone().into(),
                        }],
                    };
                    let path_with_sl = join_patterns(path_gp.clone(), sl_gp);
                    path_patterns.push(GraphPattern::Union {
                        left: Box::new(path_gp),
                        right: Box::new(path_with_sl),
                    });
                    return Ok(());
                }
            }
            path_patterns.push(path_gp);
            Ok(())
        } else {
            // No range quantifier: single or multi-type, treat as plain triple.
            let pred = self.iri(&rel.rel_types[0]);
            if multi_type {
                // Multi-type without range: use property path Alternative.
                let types: Vec<PPE> = rel
                    .rel_types
                    .iter()
                    .map(|t| PPE::from(self.iri(t)))
                    .collect();
                let path = types
                    .into_iter()
                    .reduce(|a, b| PPE::Alternative(Box::new(a), Box::new(b)))
                    .expect("multi_type has ≥2 types");
                let path = if rel.direction == Direction::Both {
                    // Undirected multi-type: Alternative(types) | Reverse(Alternative(types))
                    PPE::Alternative(
                        Box::new(path.clone()),
                        Box::new(PPE::Reverse(Box::new(path))),
                    )
                } else {
                    path
                };
                let (subj, obj) = match rel.direction {
                    Direction::Left => (dst.clone(), src.clone()),
                    _ => (src.clone(), dst.clone()),
                };
                path_patterns.push(GraphPattern::Path {
                    subject: subj,
                    path,
                    object: obj,
                });
                if let Some(ref var_name) = rel.variable {
                    self.edge_map.insert(
                        var_name.clone(),
                        EdgeInfo {
                            src: src.clone(),
                            pred,
                            pred_var: None,
                            dst: dst.clone(),
                            reif_var: None,
                            null_check_var: None,
                            eid_var: None,
                            binding_generation: self.with_generation,
                        },
                    );
                }
                Ok(())
            } else {
                self.emit_edge_triple(rel, src, dst, pred, triples, path_patterns)
            }
        }
    }

    /// Emit a single-hop edge triple (no path expression) and handle inline properties.
    fn emit_edge_triple(
        &mut self,
        rel: &RelationshipPattern,
        src: &TermPattern,
        dst: &TermPattern,
        pred: NamedNode,
        triples: &mut Vec<TriplePattern>,
        path_patterns: &mut Vec<GraphPattern>,
    ) -> Result<(), PolygraphError> {
        use crate::ast::cypher::Direction;

        match rel.direction {
            Direction::Left => triples.push(TriplePattern {
                subject: dst.clone(),
                predicate: pred.clone().into(),
                object: src.clone(),
            }),
            Direction::Right => triples.push(TriplePattern {
                subject: src.clone(),
                predicate: pred.clone().into(),
                object: dst.clone(),
            }),
            Direction::Both => {
                // Undirected (-- or <-->): match either direction via UNION.
                // Use FILTER(?src != ?dst) in the backward branch to avoid
                // duplicate results for self-loops (where src == dst).
                let fwd = GraphPattern::Bgp {
                    patterns: vec![TriplePattern {
                        subject: src.clone(),
                        predicate: pred.clone().into(),
                        object: dst.clone(),
                    }],
                };
                let bwd_triple = GraphPattern::Bgp {
                    patterns: vec![TriplePattern {
                        subject: dst.clone(),
                        predicate: pred.clone().into(),
                        object: src.clone(),
                    }],
                };
                // Apply filter to avoid duplicate for self-loops.
                let filter_expr =
                    if let (TermPattern::Variable(s), TermPattern::Variable(d)) = (src, dst) {
                        Some(SparExpr::Not(Box::new(SparExpr::Equal(
                            Box::new(SparExpr::Variable(s.clone())),
                            Box::new(SparExpr::Variable(d.clone())),
                        ))))
                    } else {
                        None
                    };
                let bwd = if let Some(f) = filter_expr {
                    GraphPattern::Filter {
                        expr: f,
                        inner: Box::new(bwd_triple),
                    }
                } else {
                    bwd_triple
                };
                // If the relationship has a name, BIND a synthetic edge-identity
                // variable in each UNION branch (canonical stored-triple order).
                let (fwd, bwd) = if let Some(rel_var_name) = &rel.variable {
                    let eid = Variable::new_unchecked(format!("__eid_{}", rel_var_name));
                    let pred_expr = SparExpr::Literal(SparLit::new_simple_literal(pred.as_str()));
                    let fwd_eid = build_edge_id_expr(src, pred_expr.clone(), dst);
                    let bwd_eid = build_edge_id_expr(dst, pred_expr, src);
                    let fwd = GraphPattern::Extend {
                        inner: Box::new(fwd),
                        variable: eid.clone(),
                        expression: fwd_eid,
                    };
                    let bwd = GraphPattern::Extend {
                        inner: Box::new(bwd),
                        variable: eid,
                        expression: bwd_eid,
                    };
                    (fwd, bwd)
                } else {
                    (fwd, bwd)
                };
                path_patterns.push(GraphPattern::Union {
                    left: Box::new(fwd),
                    right: Box::new(bwd),
                });
            }
        }

        // Track this hop for pairwise relationship-isomorphism FILTER generation.
        {
            use spargebra::term::NamedNodePattern;
            let pred_pattern = NamedNodePattern::NamedNode(pred.clone());
            let instances: Vec<EdgeIsoSlot> = match rel.direction {
                Direction::Right => vec![(src.clone(), pred_pattern, dst.clone())],
                Direction::Left => vec![(dst.clone(), pred_pattern, src.clone())],
                Direction::Both => vec![
                    (src.clone(), pred_pattern.clone(), dst.clone()),
                    (dst.clone(), pred_pattern, src.clone()),
                ],
            };
            self.track_iso_hop(instances);
        }

        // Register edge info for later `r.prop` and `r IS NULL` resolution.
        if let Some(ref var_name) = rel.variable {
            let reif_var = if self.rdf_star {
                None
            } else {
                Some(self.fresh_var(&format!("reif_{var_name}")))
            };
            // Introduce a marker variable bound to the predicate IRI.
            // This enables IS NULL / IS NOT NULL checks on typed relationship
            // variables: when the edge is found, ?var_marker is bound; when the
            // OPTIONAL MATCH containing the edge fails, ?var_marker is unbound.
            let marker = self.fresh_var(&format!("{var_name}_marker"));
            // Build eid_var for typed relationships (undirected get it from
            // the BIND above; directed get a simple BIND too).
            let eid = if matches!(rel.direction, Direction::Both) {
                // Already BIND'd in each UNION branch above.
                Some(Variable::new_unchecked(format!("__eid_{var_name}")))
            } else {
                // Directed typed: BIND edge identity based on known direction.
                let eid = Variable::new_unchecked(format!("__eid_{var_name}"));
                let pred_expr = SparExpr::Literal(SparLit::new_simple_literal(pred.as_str()));
                let (actual_s, actual_o) = match rel.direction {
                    Direction::Left => (dst, src),
                    _ => (src, dst),
                };
                // Merge marker and eid into one Extend chain (one BIND group) to avoid
                // the spargebra serialization issue with sequential `{ BIND } { BIND }` groups
                // causing oxigraph parse errors when followed by a bare BIND alias.
                let marker_extend = GraphPattern::Extend {
                    inner: Box::new(empty_bgp()),
                    variable: marker.clone(),
                    expression: SparExpr::Literal(SparLit::new_typed_literal(
                        pred.as_str(),
                        NamedNode::new_unchecked("http://www.w3.org/2001/XMLSchema#anyURI"),
                    )),
                };
                path_patterns.push(GraphPattern::Extend {
                    inner: Box::new(marker_extend),
                    variable: eid.clone(),
                    expression: build_edge_id_expr(actual_s, pred_expr, actual_o),
                });
                Some(eid)
            };
            if matches!(rel.direction, Direction::Both) {
                // For undirected, only push marker separately (eid was already pushed in each UNION branch).
                path_patterns.push(GraphPattern::Extend {
                    inner: Box::new(empty_bgp()),
                    variable: marker.clone(),
                    expression: SparExpr::Literal(SparLit::new_typed_literal(
                        pred.as_str(),
                        NamedNode::new_unchecked("http://www.w3.org/2001/XMLSchema#anyURI"),
                    )),
                });
            }
            self.edge_map.insert(
                var_name.clone(),
                EdgeInfo {
                    // Use the actual RDF subject/object order (accounting for direction).
                    // For Direction::Left, the arrow points left so the actual triple is
                    // `dst -[pred]-> src` (right node is the RDF subject, left is object).
                    src: match rel.direction {
                        Direction::Left => dst.clone(),
                        _ => src.clone(),
                    },
                    pred: pred.clone(),
                    pred_var: None,
                    dst: match rel.direction {
                        Direction::Left => src.clone(),
                        _ => dst.clone(),
                    },
                    reif_var,
                    null_check_var: Some(marker),
                    eid_var: eid,
                    binding_generation: self.with_generation,
                },
            );
        }

        // Inline relationship properties.
        if let Some(ref props) = rel.properties {
            if !props.is_empty() {
                let mut prop_pairs: Vec<(NamedNode, TermPattern)> = Vec::new();
                for (key, val_expr) in props {
                    let obj = self.expr_to_ground_term(val_expr)?;
                    prop_pairs.push((self.iri(key), obj));
                }

                if self.rdf_star {
                    let reif_var = self.fresh_var("__rdf12_reif");
                    // Inline property patterns use the actual RDF subject/object order.
                    let (prop_src, prop_dst) = match rel.direction {
                        Direction::Left => (dst.clone(), src.clone()),
                        _ => (src.clone(), dst.clone()),
                    };
                    let extra = rdf_mapping::rdf_star::all_property_triples(
                        prop_src,
                        spargebra::term::NamedNodePattern::NamedNode(pred.clone()),
                        prop_dst,
                        &prop_pairs,
                        reif_var,
                    );
                    triples.extend(extra);
                } else {
                    let reif_var = rel
                        .variable
                        .as_ref()
                        .and_then(|v| self.edge_map.get(v))
                        .and_then(|ei| ei.reif_var.clone())
                        .unwrap_or_else(|| self.fresh_var("reif"));
                    let (prop_src, prop_dst) = match rel.direction {
                        Direction::Left => (dst.clone(), src.clone()),
                        _ => (src.clone(), dst.clone()),
                    };
                    let extra = rdf_mapping::reification::all_triples(
                        &reif_var,
                        prop_src,
                        pred.clone(),
                        prop_dst,
                        &prop_pairs,
                    );
                    triples.extend(extra);
                }
            }
        }

        Ok(())
    }

    /// Emit a bounded path `*lower..upper` as a UNION of explicit fixed-length chain patterns.
    ///
    /// Each hop-count from `lower` to `upper` produces one alternative in the UNION.
    #[allow(clippy::too_many_arguments)]
    fn emit_bounded_path_union(
        &mut self,
        rel: &RelationshipPattern,
        src: &TermPattern,
        dst: &TermPattern,
        base_ppe: &spargebra::algebra::PropertyPathExpression,
        lower: u64,
        upper: u64,
        _triples: &mut Vec<TriplePattern>,
        path_patterns: &mut Vec<GraphPattern>,
    ) -> Result<(), PolygraphError> {
        use crate::ast::cypher::Direction;
        use spargebra::algebra::PropertyPathExpression as PPE;

        let type_iri = if rel.rel_types.is_empty() {
            self.iri("__rel")
        } else {
            self.iri(&rel.rel_types[0])
        };

        // Determine effective subject/object based on direction.
        let (effective_src, effective_dst) = match rel.direction {
            Direction::Left => (dst.clone(), src.clone()),
            _ => (src.clone(), dst.clone()),
        };

        // If the requested range is empty (lower > upper) emit a pattern that
        // matches no rows so surrounding WHERE yields zero solutions.
        if lower > upper {
            path_patterns.push(GraphPattern::Filter {
                expr: SparExpr::Literal(SparLit::new_typed_literal(
                    "false",
                    NamedNode::new_unchecked(XSD_BOOLEAN),
                )),
                inner: Box::new(empty_bgp()),
            });
            return Ok(());
        }

        let mut union_patterns: Vec<GraphPattern> = Vec::new();

        for hop_count in lower..=upper {
            if hop_count == 0 {
                // Zero-hop: src = dst = the same graph node.
                // Semantics: (a)-[*0]->(c) binds c = a for every node a.
                //
                // Strategy: emit the node-sentinel triple for effective_src to
                // enumerate all Cypher nodes (when src is unbound) or to verify
                // the node exists (when src is already bound by an outer pattern).
                // Then BIND effective_dst = effective_src to equate both ends.
                //
                // The node sentinel triple is: ?node <base:__node> <base:__node>
                let sentinel_iri = self.iri("__node");
                let sentinel_triple = TriplePattern {
                    subject: effective_src.clone(),
                    predicate: spargebra::term::NamedNodePattern::NamedNode(sentinel_iri.clone()),
                    object: TermPattern::NamedNode(sentinel_iri),
                };
                let bgp = GraphPattern::Bgp {
                    patterns: vec![sentinel_triple],
                };
                let zero_pattern =
                    match (&effective_src, &effective_dst) {
                        // Both are variables and they differ: extend binding.
                        (TermPattern::Variable(s), TermPattern::Variable(d)) if s != d => {
                            GraphPattern::Extend {
                                inner: Box::new(bgp),
                                variable: d.clone(),
                                expression: SparExpr::Variable(s.clone()),
                            }
                        }
                        // Same variable or named nodes: just the sentinel triple.
                        _ => bgp,
                    };
                union_patterns.push(zero_pattern);
            } else if hop_count == 1 {
                // Single hop: emit as a plain path (allows multi-direction).
                // For Left: effective_src=dst, effective_dst=src (already swapped) — forward path.
                let p = match rel.direction {
                    Direction::Both => PPE::Alternative(
                        Box::new(base_ppe.clone()),
                        Box::new(PPE::Reverse(Box::new(base_ppe.clone()))),
                    ),
                    _ => base_ppe.clone(), // Left: no extra Reverse; swap handles direction
                };
                union_patterns.push(GraphPattern::Path {
                    subject: effective_src.clone(),
                    path: p,
                    object: effective_dst.clone(),
                });
            } else {
                // Multiple hops: chain via intermediate vars.
                // For undirected patterns, enumerate all 2^N direction combos
                // with pairwise edge-uniqueness FILTERs.
                let is_undirected = rel.direction == Direction::Both;
                if is_undirected {
                    // Pre-generate intermediate variables (shared across combos).
                    let intermediates: Vec<TermPattern> = (0..hop_count - 1)
                        .map(|k| self.fresh_var(&format!("mid{}", k)).into())
                        .collect();
                    let is_untyped = rel.rel_types.is_empty();

                    let mut union_arms: Vec<GraphPattern> = Vec::new();
                    for combo in 0..(1u64 << hop_count) {
                        let mut hop_parts: Vec<GraphPattern> = Vec::new();
                        let mut hop_subjs: Vec<TermPattern> = Vec::new();
                        let mut hop_objs: Vec<TermPattern> = Vec::new();

                        let mut prev = effective_src.clone();
                        for hop in 0..hop_count {
                            let next: TermPattern = if (hop as usize) < intermediates.len() {
                                intermediates[hop as usize].clone()
                            } else {
                                effective_dst.clone()
                            };
                            let is_forward = (combo >> hop) & 1 == 0;
                            let (subj, obj) = if is_forward {
                                (prev.clone(), next.clone())
                            } else {
                                (next.clone(), prev.clone())
                            };
                            hop_subjs.push(subj.clone());
                            hop_objs.push(obj.clone());
                            if is_untyped {
                                hop_parts.push(GraphPattern::Path {
                                    subject: subj,
                                    path: base_ppe.clone(),
                                    object: obj,
                                });
                            } else {
                                hop_parts.push(GraphPattern::Bgp {
                                    patterns: vec![TriplePattern {
                                        subject: subj,
                                        predicate: type_iri.clone().into(),
                                        object: obj,
                                    }],
                                });
                            }
                            prev = next;
                        }

                        let mut arm = hop_parts
                            .into_iter()
                            .reduce(join_patterns)
                            .unwrap_or_else(empty_bgp);

                        // Pairwise edge-uniqueness: FILTER NOT(si=sj AND oi=oj)
                        for i in 0..hop_count as usize {
                            for j in (i + 1)..hop_count as usize {
                                let si_eq_sj = SparExpr::Equal(
                                    Box::new(term_to_sparexpr(&hop_subjs[i])),
                                    Box::new(term_to_sparexpr(&hop_subjs[j])),
                                );
                                let oi_eq_oj = SparExpr::Equal(
                                    Box::new(term_to_sparexpr(&hop_objs[i])),
                                    Box::new(term_to_sparexpr(&hop_objs[j])),
                                );
                                let same = SparExpr::And(Box::new(si_eq_sj), Box::new(oi_eq_oj));
                                arm = GraphPattern::Filter {
                                    expr: SparExpr::Not(Box::new(same)),
                                    inner: Box::new(arm),
                                };
                            }
                        }

                        union_arms.push(arm);
                    }

                    let combined = union_arms
                        .into_iter()
                        .reduce(|a, b| GraphPattern::Union {
                            left: Box::new(a),
                            right: Box::new(b),
                        })
                        .unwrap_or_else(empty_bgp);
                    union_patterns.push(combined);
                } else {
                    // Directed multi-hop: simple chain of triple/path patterns.
                    let is_untyped = rel.rel_types.is_empty();
                    let mut parts: Vec<GraphPattern> = Vec::new();
                    let mut prev = effective_src.clone();
                    for hop in 0..hop_count {
                        let next: TermPattern = if hop == hop_count - 1 {
                            effective_dst.clone()
                        } else {
                            self.fresh_var(&format!("mid{}", hop)).into()
                        };
                        if is_untyped {
                            // Untyped: use NPS path per hop.
                            parts.push(GraphPattern::Path {
                                subject: prev.clone(),
                                path: base_ppe.clone(),
                                object: next.clone(),
                            });
                        } else {
                            parts.push(GraphPattern::Bgp {
                                patterns: vec![TriplePattern {
                                    subject: prev.clone(),
                                    predicate: type_iri.clone().into(),
                                    object: next.clone(),
                                }],
                            });
                        }
                        prev = next;
                    }
                    let mut chain = parts
                        .into_iter()
                        .reduce(join_patterns)
                        .unwrap_or_else(empty_bgp);
                    // For untyped, filter out literal endpoints.
                    if is_untyped {
                        if let TermPattern::Variable(v) = &effective_dst {
                            chain = GraphPattern::Filter {
                                expr: SparExpr::Not(Box::new(SparExpr::FunctionCall(
                                    spargebra::algebra::Function::IsLiteral,
                                    vec![SparExpr::Variable(v.clone())],
                                ))),
                                inner: Box::new(chain),
                            };
                        }
                    }
                    union_patterns.push(chain);
                }
            }
        }

        // Combine with UNION.
        let combined = union_patterns
            .into_iter()
            .reduce(|a, b| GraphPattern::Union {
                left: Box::new(a),
                right: Box::new(b),
            })
            .unwrap_or_else(empty_bgp);
        path_patterns.push(combined);
        Ok(())
    }

    /// Emit bounded path union with RDF-star per-hop property annotation filters.
    ///
    /// Each hop in the chain includes the base typed triple AND an annotation
    /// triple for each property constraint (e.g., `<< s <T> o >> <year> 1988 .`).
    fn emit_bounded_path_union_with_props(
        &mut self,
        rel: &RelationshipPattern,
        src: &TermPattern,
        dst: &TermPattern,
        lower: u64,
        upper: u64,
        path_patterns: &mut Vec<GraphPattern>,
    ) -> Result<(), PolygraphError> {
        use crate::ast::cypher::Direction;

        let type_iri = self.iri(&rel.rel_types[0]);
        let (effective_src, effective_dst) = match rel.direction {
            Direction::Left => (dst.clone(), src.clone()),
            _ => (src.clone(), dst.clone()),
        };

        let props = rel.properties.as_ref().unwrap();
        let mut union_patterns: Vec<GraphPattern> = Vec::new();

        for hop_count in lower..=upper {
            let mut parts: Vec<GraphPattern> = Vec::new();
            let mut prev = effective_src.clone();

            for hop in 0..hop_count {
                let next: TermPattern = if hop == hop_count - 1 {
                    effective_dst.clone()
                } else {
                    self.fresh_var(&format!("mid{}", hop)).into()
                };

                // Base edge triple: ?prev <T> ?next
                let edge_triple = TriplePattern {
                    subject: prev.clone(),
                    predicate: type_iri.clone().into(),
                    object: next.clone(),
                };
                let mut hop_triples = vec![edge_triple.clone()];

                // RDF 1.2 reification-based property constraints for this hop:
                // ?reif rdf:reifies <<(?prev <T> ?next)>> . ?reif <prop> val . ...
                if self.rdf_star {
                    let reif_var = self.fresh_var("__rdf12_reif");
                    let rdf_reifies = NamedNode::new_unchecked(
                        "http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies",
                    );
                    let edge_term = spargebra::term::TermPattern::Triple(Box::new(TriplePattern {
                        subject: prev.clone(),
                        predicate: type_iri.clone().into(),
                        object: next.clone(),
                    }));
                    // Add rdf:reifies triple once per hop.
                    hop_triples.push(TriplePattern {
                        subject: reif_var.clone().into(),
                        predicate: rdf_reifies.into(),
                        object: edge_term,
                    });
                    for (key, val_expr) in props {
                        if let Expression::Literal(lit) = val_expr {
                            if let Ok(sparql_lit) = self.translate_literal(lit) {
                                hop_triples.push(TriplePattern {
                                    subject: reif_var.clone().into(),
                                    predicate: self.iri(key).into(),
                                    object: spargebra::term::TermPattern::Literal(sparql_lit),
                                });
                            }
                        }
                    }
                } else {
                    // RDF reification (classic) — not used in TCK engine but kept for completeness.
                    for (key, val_expr) in props {
                        if let Expression::Literal(lit) = val_expr {
                            if let Ok(sparql_lit) = self.translate_literal(lit) {
                                let anno_triple = TriplePattern {
                                    subject: spargebra::term::TermPattern::Triple(Box::new(
                                        spargebra::term::TriplePattern {
                                            subject: prev.clone(),
                                            predicate: type_iri.clone().into(),
                                            object: next.clone(),
                                        },
                                    )),
                                    predicate: self.iri(key).into(),
                                    object: spargebra::term::TermPattern::Literal(sparql_lit),
                                };
                                hop_triples.push(anno_triple);
                            }
                        }
                    }
                }

                parts.push(GraphPattern::Bgp {
                    patterns: hop_triples,
                });
                prev = next;
            }

            let chain = parts
                .into_iter()
                .reduce(join_patterns)
                .unwrap_or_else(empty_bgp);
            union_patterns.push(chain);
        }

        let combined = union_patterns
            .into_iter()
            .reduce(|a, b| GraphPattern::Union {
                left: Box::new(a),
                right: Box::new(b),
            })
            .unwrap_or_else(empty_bgp);
        path_patterns.push(combined);
        Ok(())
    }

}
